### ISSUE TITLE
core-image-minimal-qemux86-64 does not boot in VirtualBox

### ISSUE THREAD

**Issue by gmacario** [gmacario/genivi-demo-platform#1]
Built from https://github.com/gmacario/genivi-demo-platform/tree/dev-qemux86-64 commit e01ebe7838170ef45a920b43f11dcd02865d2d13

Steps to reproduce:

From the Oracle VM VirtualBox Manager, create a new VM
- Name: core-image-minimal-qemux86-64
- Type: Linux
- Version: Other Linux (64-bit)

Memory size: 1024 MB

Hard disk: Use an existing virtual hard disk file
- File name: .../core-image-minimal-qemux86-64.vmdk

Click "Create"

From the Oracle VM VirtualBox Manager, start the VM

Result:

```
...
VFS: Unable to mount root fs on unknown-block(0,0)
User configuration error - no valid root filesystem found
Kernel panic - not syncing: Invalid configuration from end user prevents continuing
...
```

I was unable to scroll up in the boot log, but I presume the kernel cmdline does not properly define `root=xxx`

**Comment by gmacario** [comment]
I managed to have core-image-minimal-qemux86-64.vmdk boot in VirtualBox by performing the following settings:

From the Oracle VM VirtualBox Manager, create a new Virtual Machine
- Name: core-image-minimal-qemux86-64
- Type: Linux
- Version: Other Linux (64-bit)

Memory size: 1024 MB

Hard disk: Do not add a virtual hard disk

Use an existing virtual hard disk file

Select "Create", then "Continue"

From the Oracle VM VirtualBox Manager, change VM settings

Under Storage > Controller: SATA > Add new storage attachment > Add Hard Disk

Choose existing disk

Virtual hard disk file: .../core-image-minimal-qemux86-64.vmdk

Click "OK"

From the Oracle VM VirtualBox Manager, start the VM

Result:

![capture-20151114-1623](https://cloud.githubusercontent.com/assets/75182/11164285/225eebb2-8aec-11e5-89b6-685f0b0fd9a2.PNG)

You may then login as user `root` (there is no default password)

Closing issue

**Comment by AkbarAlam** [comment]
where i can find this image ?

**Comment by gmacario** [comment]
Hello,

This repository is obsolete, please look at upstream https://github.com/GENIVI/GENIVI-Dev-platform instead.

Hope it helps, 
Gianpaolo
